### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by b44p** [California-Data-Collaborative/cadc_reservoir_explorer#2]
Hey @dmarulli - could you add  a brief overview writeup for this that includes ...the data items that powers the viz?

**Comment by patwater** [comment]
The parsing actually was courtesy of @anthonycarlos92 .  See here for his Seed Consulting code: https://github.com/anthonycarlos92/waterlog_project_rest_api/blob/master/helpers/swp_reservoir_scraper.py

Here's the key bit where he cycles through the reservoir id's:

requests.get('http://cdec.water.ca.gov/cgi-progs/profile?s=%s&type=dam' % station_id)
    request_soupified = BeautifulSoup(swp_client_request_meta_data.text, "html.parser")

Pulls from CDEC [here](http://cdec.water.ca.gov/reservoir.html) and see [here for more water resources data sources that would be cool to parse and make slick viz's of in the future](https://mavensnotebook.com/the-notebook-file-cabinet/water-and-hydrology-resources-on-the-internet-reservoir-conditions-precipitation-indexes-snow-charts-drought-maps-and-more/)

**Comment by christophertull** [comment]
Could probably repurpose some of that code into parsekit format if desired.

**Comment by patwater** [comment]
This still needed? If not can we close?
