### ISSUE TITLE
AWS keys in public repo.

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/cadc_reservoir_explorer#4]
FYI @vishelar @Alan-F @dmarulli  we got an alert from AWS about our AWS access keys being publicly accessible from this repo. I deleted the key in question, so you will need to create a new one. 

However, probably best to avoid having access keys pushed to a public repo. Easiest way around this would probably be to pull the parser code into a separate **private** repo and leave the JS code here.

**Comment by vishelar** [comment]
I am extremely sorry for this critical mistake. I will make sure that this kind of mistake never happens again. I have made changes to the parser code to remove the AWS access keys.

**Comment by christophertull** [comment]
Thanks for the quick response! I think all is well this time. I created a new private repo for the parser code [here](https://github.com/California-Data-Collaborative/parser_reservoir_explorer) and will add collaborators now.
