### ISSUE TITLE
Scheduling regular updates 

### ISSUE THREAD

**Issue by patwater** [California-Data-Collaborative/cadc_reservoir_explorer#6]
Here's a getting started guide with Apache Airflow: https://medium.com/a-r-g-o/installing-apache-airflow-on-ubuntu-aws-6ebac15db211

Here's the old parsekit scripts for reference which detail the specific links and fields from the state data: https://github.com/California-Data-Collaborative/cadc_reservoir_explorer/tree/master/ParseKit%20Scripts

**Comment by patwater** [comment]
@mike-amodeo good chatting and pulling in the historical data and deploying locally sounds like a good start. This provides a nice technical overview of some of the technical requirements for regular data updates: https://github.com/California-Data-Collaborative/cadc_reservoir_explorer/projects 

CC @dmarulli

**Comment by patwater** [comment]
@mike-amodeo @dmarulli can we close this for the reservoir data updates?

**Comment by dmarulli** [comment]
yep. closing now.
